(ns hxgm30.agent.model.bigfive.inventory)

(def questions-short
  {:title "Five Factor Model (Big Five) Short Inventory"
   :questions [{:question "is reserved"
                :domain-key :E
                :reversed? true}
               {:question "is generally trusting"
                :domain-key :A
                :reversed? false}
               {:question "tends to be lazy"
                :domain-key :C
                :reversed? true}
               {:question "is relaxed, handles stress well"
                :domain-key :N
                :reversed? true}
               {:question "has few artistic interests"
                :domain-key :O
                :reversed? true}
               {:question "is outgoing, sociable"
                :domain-key :E
                :reversed? false}
               {:question "tends to find fault with others"
                :domain-key :A
                :reversed? true}
               {:question "does a thorough job"
                :domain-key :C
                :reversed? false}
               {:question "gets nervous easily"
                :domain-key :N
                :reversed? false}
               {:question "has an active imagination"
                :domain-key :O
                :reversed? false}]})

(def questions-long
  {:title "Five Factor Model (Big Five) Long Inventory"
   :questions [{:number 1
                :question "is talkative"
                :domain-key :E
                :reversed? false}
               {:number 2
                :question "tends to find fault with others"
                :domain-key :A
                :reversed? true}
               {:number 3
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 4
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 5
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 6
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 7
                :question "XXX"
                :domain-key :A
                :reversed? false}
               {:number 8
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 9
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 10
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 11
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 12
                :question "XXX"
                :domain-key :A
                :reversed? true}
               {:number 13
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 14
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 15
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 16
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 17
                :question "XXX"
                :domain-key :A
                :reversed? false}
               {:number 18
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 19
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 20
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 21
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 22
                :question "XXX"
                :domain-key :A
                :reversed? false}
               {:number 23
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 24
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 25
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 26
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 27
                :question "XXX"
                :domain-key :A
                :reversed? true}
               {:number 28
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 29
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 30
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 31
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 32
                :question "XXX"
                :domain-key :A
                :reversed? false}
               {:number 33
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 34
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 35
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 36
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 37
                :question "XXX"
                :domain-key :A
                :reversed? true}
               {:number 38
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 39
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 40
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 41
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 42
                :question "XXX"
                :domain-key :A
                :reversed? false}
               {:number 43
                :question "XXX"
                :domain-key :E
                :reversed? true}
               {:number 44
                :question "XXX"
                :domain-key :E
                :reversed? true}
   ]})
